name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup node and yarn
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn build
    name: upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist/*.js
          dist/*.css