name: Test
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup node and yarn
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn lint
